[project]
name = "agent-sdk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai>=0.27.10",
    "openai-agents>=0.2.10",
    "pip>=25.2",
    "python-dotenv>=1.1.1",
    "web-search-agent>=0.2.0",
]
